# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# Action name
name: Upload Python Package

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    # job name
    name: publish python package to PYPI

    if: |
      github.event.pull_request.merged == true && 
      github.event.pull_request.base.ref == 'master'

    # machine environment
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "^3.6"

      # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install poetry

      # build and publish
      - name: Build and publish
        env:
          username: __token__
          password: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          twine upload --verbose --username ${{ env.username }} --password ${{ env.password }} --repository pypi dist/*
